import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import '../assets/styles/globals.css'

export const metadata: Metadata = {
  title: 'Wizard ON',
  description: 'Generated by create next app',
}

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-open-sans',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={openSans.variable}>
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  )
}
